// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnCdC4KAfKdMkVnEWdMIEOg_CdWpGx3r0',
    appId: '1:561416647525:web:02798da1d8a552a489a78c',
    messagingSenderId: '561416647525',
    projectId: 'spiritual-streak',
    authDomain: 'spiritual-streak.firebaseapp.com',
    storageBucket: 'spiritual-streak.appspot.com',
    measurementId: 'G-SCRPHDMQ69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTuWrXZ_M4_h9b4hpAOCRqF1zo6LY5-hM',
    appId: '1:561416647525:android:700806a2ee13963f89a78c',
    messagingSenderId: '561416647525',
    projectId: 'spiritual-streak',
    storageBucket: 'spiritual-streak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mny_5WIKqfEUP2fbzSffYhB05-UWSJk',
    appId: '1:561416647525:ios:91c287559290ec7589a78c',
    messagingSenderId: '561416647525',
    projectId: 'spiritual-streak',
    storageBucket: 'spiritual-streak.appspot.com',
    iosClientId: '561416647525-sl9j7uu7d2m1plhj2nghh6tq8813ao5u.apps.googleusercontent.com',
    iosBundleId: 'tylerchristensen.com.spiritualStreak',
  );
}
